export const links = [
  {
    name: "mercury",
    href: "/planet/mercury",
    color: "bg-mercury",
    desktopStyle: "hover:text-mercury hover:border-mercury",
    activeStyle: "text-mercury lg:border-mercury",
  },
  {
    name: "venus",
    href: "/planet/venus",
    color: "bg-venus",
    desktopStyle: "hover:text-venus hover:border-venus",
    activeStyle: "text-venus lg:border-venus",
  },
  {
    name: "earth",
    href: "/planet/earth",
    color: "bg-earth",
    desktopStyle: "hover:text-earth hover:border-earth",
    activeStyle: "text-earth lg:border-earth",
  },
  {
    name: "mars",
    href: "/planet/mars",
    color: "bg-mars",
    desktopStyle: "hover:text-mars lg:hover:border-mars",
    activeStyle: "text-mars lg:border-mars",
  },
  {
    name: "jupiter",
    href: "/planet/jupiter",
    color: "bg-jupiter",
    desktopStyle: "hover:text-jupiter lg:hover:border-jupiter",
    activeStyle: "text-jupiter lg:border-jupiter",
  },
  {
    name: "saturn",
    href: "/planet/saturn",
    color: "bg-saturn",
    desktopStyle: "hover:text-saturn lg:hover:border-saturn",
    activeStyle: "text-saturn lg:border-saturn",
  },
  {
    name: "uranus",
    href: "/planet/uranus",
    color: "bg-uranus",
    desktopStyle: "hover:text-uranus lg:hover:border-uranus",
    activeStyle: "text-uranus lg:border-uranus",
  },
  {
    name: "neptune",
    href: "/planet/neptune",
    color: "bg-neptune",
    desktopStyle: "hover:text-neptune lg:hover:border-neptune",
    activeStyle: "text-neptune lg:border-neptune",
  },
];
